### PR TITLE
Fixed properly checking club_committee status

### LINKED ISSUE #1: Plugin doesn't properly check club_committee status
https://github.com/SWAuk/plg_swa_viewlevels/blob/master/src/viewlevels.php#L61

### PR DESCRIPTION
**Pull request by oshotton**
Fixes #1

### CODE REVIEW

File: src/viewlevels.php [hunk 1]
```diff
@@ -58,7 +58,9 @@ function onJAccessGetAuthorisedViewLevels( $userId, &$authorised )
 			return;
 		}
 
-		if( is_object( $member ) && $member->club_committee && !empty( $member->club_committee ) ){
+		// club_committee is "0", when not in the committee, which will evaluate to false 
+		// or, when they are in the committee, is a string that will evaluate to true
+		if( is_object( $member ) && $member->club_committee && $member->club_committee ){
```
Comment (addshore) [inline src/viewlevels.php]: Dont need to do $member->club_committee && $member->club_committee twice here

**Review by addshore — CHANGES_REQUESTED** [review]

**Comment by addshore** [comment]
When you deploy this will you change all empty and NULL values to be 0?

**Comment by oshotton** [comment]
Already done for fix 165 on the com_sea repo:
https://github.com/SWAuk/com_swa/pull/165
